[project]
name = "deeplearningnotes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "stone", email = "2398391057@qq.com" }
]
requires-python = ">=3.14"
dependencies = [
    "dnnlpy>=2026.7.21",
    "jupyter>=1.1.1",
    "jupyterlab>=4.6.3",
    "torch>=2.13.0,<2.14.0",
]
